<a href="https://colab.research.google.com/github/abidshafee/Python-mini-projects/blob/main/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
grid = [[0, 0, 1, 0, 0,4, 6, 0, 0],
        [8, 2, 7, 1, 0, 3, 5, 0, 9],
        [0, 4, 9, 5, 2, 0, 0, 3, 0],
        [2, 0, 0, 0, 0, 0, 0, 0, 6],
        [7, 0, 0, 0, 1, 6, 0, 8, 4],
        [0, 0, 0, 3, 8, 2, 0, 0, 7],
        [0, 0, 0, 0, 0, 8, 0, 0, 0],
        [0, 8, 5, 0, 0, 0, 7, 6, 3],
        [0, 7, 4, 0, 5, 0, 9, 0, 8]]

In [2]:
print(grid)

[[0, 0, 1, 0, 0, 4, 6, 0, 0], [8, 2, 7, 1, 0, 3, 5, 0, 9], [0, 4, 9, 5, 2, 0, 0, 3, 0], [2, 0, 0, 0, 0, 0, 0, 0, 6], [7, 0, 0, 0, 1, 6, 0, 8, 4], [0, 0, 0, 3, 8, 2, 0, 0, 7], [0, 0, 0, 0, 0, 8, 0, 0, 0], [0, 8, 5, 0, 0, 0, 7, 6, 3], [0, 7, 4, 0, 5, 0, 9, 0, 8]]


### way to converting 2d grid to numpy n-dimentional array

In [3]:
import numpy as np
nd_grid = np.matrix(grid)
print(nd_grid)

[[0 0 1 0 0 4 6 0 0]
 [8 2 7 1 0 3 5 0 9]
 [0 4 9 5 2 0 0 3 0]
 [2 0 0 0 0 0 0 0 6]
 [7 0 0 0 1 6 0 8 4]
 [0 0 0 3 8 2 0 0 7]
 [0 0 0 0 0 8 0 0 0]
 [0 8 5 0 0 0 7 6 3]
 [0 7 4 0 5 0 9 0 8]]


check where in a certain position we can put a right number.

![image.png](https://csschoolonline.xyz/wp-content/uploads/2021/01/Sudoku_puzzle-03.png)

In [4]:
def check(y, x, n):
    global grid
    for i in range(0, 9):
        if grid[y][i] == n:
          return False
    for i in range(0, 9):
        if grid[i][x] == n:
          return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range (0, 3):
        for j in range (0, 3):
            if grid[y0+i][x0+j] == n:
                return False
    return True

In [6]:
check(3,1,7)

False

In [11]:
#from functools import lru_cache

#@lru_cache(maxsize = 1000)
#recursive function -> solve function call itself
def solve():
    global grid
    for y in range(9):
      for x in range(9):
        if grid[y][x] == 0:
          for n in range(1,10):
            if check(y,x,n):
              grid[y][x] = n
              solve()
              grid[y][x] = 0
          return
    print(np.matrix(grid))

In [12]:
solve()

[[5 3 1 8 9 4 6 7 2]
 [8 2 7 1 6 3 5 4 9]
 [6 4 9 5 2 7 8 3 1]
 [2 1 8 4 7 5 3 9 6]
 [7 5 3 9 1 6 2 8 4]
 [4 9 6 3 8 2 1 5 7]
 [9 6 2 7 3 8 4 1 5]
 [1 8 5 2 4 9 7 6 3]
 [3 7 4 6 5 1 9 2 8]]


In [12]:
import sys
print(sys.getrecursionlimit())

1000


In [ ]:
sys.setrecursionlimit(15000)

In [13]:
print(sys.getrecursionlimit())

1000
