<a href="https://colab.research.google.com/github/abidshafee/Python-mini-projects/blob/main/Sudoku_Solver.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
grid = [[0, 0, 1, 0, 0,4, 6, 0, 0],
        [8, 2, 7, 1, 0, 3, 5, 0, 9],
        [0, 4, 9, 5, 2, 0, 0, 3, 0],
        [2, 0, 0, 0, 0, 0, 0, 0, 6],
        [7, 0, 0, 0, 1, 6, 0, 8, 4],
        [0, 0, 0, 3, 8, 2, 0, 0, 7],
        [0, 0, 0, 0, 0, 8, 0, 0, 0],
        [0, 8, 5, 0, 0, 0, 7, 6, 3],
        [0, 7, 4, 0, 5, 0, 9, 0, 8]]

In [ ]:
print(grid)

[[0, 0, 1, 0, 0, 4, 6, 0, 0], [8, 2, 7, 1, 0, 3, 5, 0, 9], [0, 4, 9, 5, 2, 0, 0, 3, 0], [2, 0, 0, 0, 0, 0, 0, 0, 6], [7, 0, 0, 0, 1, 6, 0, 8, 4], [0, 0, 0, 3, 8, 2, 0, 0, 7], [0, 0, 0, 0, 0, 8, 0, 0, 0], [0, 8, 5, 0, 0, 0, 7, 6, 3], [0, 7, 4, 0, 5, 0, 9, 0, 8]]


### Converting grid to numpy n-dimentional array

In [ ]:
import numpy as np
grid = np.matrix(grid)
print(grid)

[[0 0 1 0 0 4 6 0 0]
 [8 2 7 1 0 3 5 0 9]
 [0 4 9 5 2 0 0 3 0]
 [2 0 0 0 0 0 0 0 6]
 [7 0 0 0 1 6 0 8 4]
 [0 0 0 3 8 2 0 0 7]
 [0 0 0 0 0 8 0 0 0]
 [0 8 5 0 0 0 7 6 3]
 [0 7 4 0 5 0 9 0 8]]


check where in a certain position we can put a right number.

![image.png](https://csschoolonline.xyz/wp-content/uploads/2021/01/Sudoku_puzzle-03.png)

In [ ]:
def check(y, x, n):
    global grid
    for i in range(0, 9):
        if grid[y][i] == n:
            return False
    for i in range(0, 9):
         if grid[i][x] == n:
             return False
    x0 = (x//3)*3
    y0 = (y//3)*3
    for i in range (0, 3):
        for j in range (0, 3):
            if grid[y0+i][x0+j] == n:
                return False
    return True